### PR TITLE
Several Things

### PR DESCRIPTION
**Pull request by CarsonF**
- PSR-4 autoloading
- PSR-2 Code styling, short array syntax, and single quotes
- Composer
  - Updated dependencies to allow minor releases
  - Removed composer.lock (It's not needed for libraries and general practice is to ignore it.)
- Travis
  - Updated to builtin composer and caching vendor dirs (should be faster now)
  - Added PHP 7.0 and HHVM. (looks like the bug with 7.0 is fixed in the dev branch of superclosure, once they tag a release, we can make not allowed to fail)
- Simplified PHPUnit config

I do have some actual features coming, but my OCD was making me twitch so I'm sending this in first :)

@hellogerard I see you don't have travis setup. Would you mind enabling it? All you have to do is create an account, and enable this repo. It will pick up the config file automatically. I did it earlier today for my fork and it only took a minute.

### CODE REVIEW

**Comment by hellogerard** [comment]
Thanks for the PR!  I pulled this branch locally, and tried running `phpunit`, but I'm getting an `PHP Fatal error:  Class 'Jobby\Helper' not found ` error. Do I need be running a certain version of PHP or `phpunit`?

**Comment by CarsonF** [comment]
Did you run `composer dump`? The autoloader changed so it needs to be rebuilt

**Comment by hellogerard** [comment]
Ah, that did it. Thanks.

**Comment by CarsonF** [comment]
Yay! I have a few more things coming this weekend. If you're thinking about tagging a release, I'd be grateful to get those in first :)

**Comment by CarsonF** [comment]
How about travis too?

**Comment by hellogerard** [comment]
No rush on a release. Be my guest!

Travis CI appears to be working!

**Pull request merged**
